name: 'Apply migrations to remote database'

on:
  push:
    branches:
      - '$default-branch'
jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    environment:
      name: Production
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      # Retrieve <project-id> from dashboard url: https://app.supabase.com/project/<project-id>
      PROJECT_ID: lgtnunvhxmklyelpqxyw
      # Required by supabase/config.toml
      SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: 'never'
      SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: 'never'
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
